# Generated by Django 5.1.2 on 2024-10-28 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('startupName', models.TextField()),
                ('description', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='photos/image1/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='photos/image2/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='photos/image3/')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
