# Generated by Django 5.1.2 on 2024-10-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='startupName',
            field=models.CharField(max_length=60),
        ),
    ]
