# Generated by Django 5.1.2 on 2024-10-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_alter_profile_startupname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
