# Generated by Django 5.1.2 on 2024-11-15 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tweet_images')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.profile')),
            ],
        ),
    ]
