# Generated by Django 5.1.2 on 2024-11-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0006_profile_date_profile_location_profile_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_No',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
